# Generated by Django 4.1.3 on 2022-11-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_menswatches_image'),
        ('auth_app', '0003_remove_profile_preferred_watches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_watches',
            field=models.ManyToManyField(to='web.menswatches'),
        ),
    ]
