# Generated by Django 4.1.3 on 2022-11-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_profile_preferred_watches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preferred_watches',
            new_name='preferred_mens_watches',
        ),
    ]
