# Generated by Django 4.1.3 on 2022-12-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
