# Generated by Django 4.1.3 on 2022-12-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_remove_profile_preferred_women_watches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preferred_mens_watches',
            new_name='preferred_watches',
        ),
    ]
