# Generated by Django 4.1.3 on 2022-12-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_sunglasses_price'),
        ('auth_app', '0017_rename_preferred_mens_watches_profile_preferred_watches'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_sunglasses',
            field=models.ManyToManyField(to='web.sunglasses'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_wallets',
            field=models.ManyToManyField(to='web.wallets'),
        ),
    ]
