# Generated by Django 4.1.3 on 2022-12-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_sunglasses_price'),
        ('auth_app', '0019_remove_profile_preferred_sunglasses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_sunglasses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_wallets',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_watches',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_sunglasses',
            field=models.ManyToManyField(to='web.sunglasses'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_wallets',
            field=models.ManyToManyField(to='web.wallets'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_watches',
            field=models.ManyToManyField(to='web.watches'),
        ),
    ]
