# Generated by Django 4.1.3 on 2022-12-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_sunglasses_price'),
        ('auth_app', '0021_remove_profile_preferred_sunglasses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_sunglasses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.sunglasses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_wallets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.wallets'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_watches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.watches'),
        ),
    ]
