# Generated by Django 4.1.3 on 2022-12-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_belts'),
        ('auth_app', '0022_alter_profile_preferred_sunglasses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_belts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.belts'),
        ),
    ]
