# Generated by Django 4.1.3 on 2022-12-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_ties'),
        ('auth_app', '0023_profile_preferred_belts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preffered_ties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ties'),
        ),
    ]
