# Generated by Django 4.1.3 on 2022-12-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_belts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_sunglasses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_ties',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_wallets',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_watches',
        ),
    ]
