# Generated by Django 4.1.3 on 2022-12-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0030_profile_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart_items',
        ),
    ]
