# Generated by Django 4.1.3 on 2022-12-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_profile_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_URL',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
