# Generated by Django 4.1.3 on 2022-12-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_remove_like_user'),
        ('auth_app', '0034_remove_profile_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.like'),
        ),
    ]
