# Generated by Django 4.1.3 on 2022-12-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0035_profile_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
    ]
