# Generated by Django 4.1.3 on 2022-12-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0040_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
