# Generated by Django 4.1.3 on 2022-11-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menswatches',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
