# Generated by Django 4.1.3 on 2022-11-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_menswatches_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomenWatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
    ]
