# Generated by Django 4.1.3 on 2022-12-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_remove_profile_preferred_women_watches'),
        ('web', '0004_delete_womenwatches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensWatches',
            new_name='Watches',
        ),
    ]
