# Generated by Django 4.1.3 on 2022-12-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_sunglasses_wallet_watches_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Wallets',
        ),
    ]
