# Generated by Django 4.1.3 on 2022-12-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_sunglasses_lens_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('material', models.CharField(choices=[('Leather', 'Leather'), ('Plastic', 'Plastic'), ('Heavy Cloth', 'Heavy Cloth')], max_length=25)),
                ('buckle_form', models.CharField(max_length=25)),
            ],
        ),
    ]
