# Generated by Django 4.1.3 on 2022-12-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_belts'),
    ]

    operations = [
        migrations.AddField(
            model_name='belts',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
