# Generated by Django 4.1.3 on 2022-12-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_belts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='belts',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
