# Generated by Django 4.1.3 on 2022-12-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_belts_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='belts',
            name='color',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
