# Generated by Django 4.1.3 on 2022-12-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_belts_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('image', models.URLField()),
                ('material', models.CharField(choices=[('Polyester', 'Polyester'), ('Wool', 'Wool')], max_length=25)),
                ('color', models.CharField(max_length=15)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
