# Generated by Django 4.1.3 on 2022-12-05 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_remove_profile_preferred_belts_and_more'),
        ('web', '0016_ties'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='liked_watches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile'),
        ),
    ]
