# Generated by Django 4.1.3 on 2022-12-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_watches_liked_watches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watches',
            name='liked_watches',
        ),
    ]
