# Generated by Django 4.1.3 on 2022-12-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_remove_profile_preferred_belts_and_more'),
        ('web', '0018_remove_watches_liked_watches'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunglasses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.sunglasses')),
                ('watches', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.watches')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile')),
            ],
        ),
    ]
