# Generated by Django 4.1.3 on 2022-12-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_cartitems_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='sunglasses',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='watches',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='sunglasses',
            field=models.ManyToManyField(blank=True, null=True, to='web.sunglasses'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='watches',
            field=models.ManyToManyField(blank=True, null=True, to='web.watches'),
        ),
    ]
