# Generated by Django 4.1.3 on 2022-12-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_remove_cartitems_sunglasses_remove_cartitems_watches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='sunglasses',
            field=models.ManyToManyField(blank=True, to='web.sunglasses'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='watches',
            field=models.ManyToManyField(blank=True, to='web.watches'),
        ),
    ]
