# Generated by Django 4.1.3 on 2022-12-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_alter_cartitems_sunglasses_alter_cartitems_watches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='sunglasses',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='watches',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
