# Generated by Django 4.1.3 on 2022-12-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_remove_profile_preferred_belts_and_more'),
        ('web', '0023_remove_cartitems_cart_remove_cartitems_sunglasses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.belts')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cart')),
                ('sunglasses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sunglasses')),
                ('ties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ties')),
                ('wallets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.wallets')),
                ('watches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.watches')),
            ],
        ),
    ]
