# Generated by Django 4.1.3 on 2022-12-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_remove_profile_preferred_belts_and_more'),
        ('web', '0024_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile'),
        ),
    ]
