# Generated by Django 4.1.3 on 2022-12-05 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_remove_profile_preferred_belts_and_more'),
        ('web', '0025_alter_cart_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='auth_app.profile'),
        ),
        migrations.AlterField(
            model_name='ties',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
