# Generated by Django 4.1.3 on 2022-12-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_cart_profile_alter_ties_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belts',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='sunglasses',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='ties',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
