# Generated by Django 4.1.3 on 2022-12-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='belts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.belts'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='sunglasses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.sunglasses'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='ties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ties'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='wallets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.wallets'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='watches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.watches'),
        ),
    ]
