# Generated by Django 4.1.3 on 2022-12-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_remove_profile_cart_items'),
        ('web', '0031_remove_cart_items_cart_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='profile',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile'),
            preserve_default=False,
        ),
    ]
