# Generated by Django 4.1.3 on 2022-12-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_cart_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
