# Generated by Django 4.1.3 on 2022-12-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_remove_cartitems_belts_remove_cartitems_sunglasses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='belts',
            field=models.ManyToManyField(blank=True, to='web.belts'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='sunglasses',
            field=models.ManyToManyField(blank=True, to='web.sunglasses'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='ties',
            field=models.ManyToManyField(blank=True, to='web.ties'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='wallets',
            field=models.ManyToManyField(blank=True, to='web.wallets'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='watches',
            field=models.ManyToManyField(blank=True, to='web.watches'),
        ),
    ]
