# Generated by Django 4.1.3 on 2022-12-07 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0034_remove_profile_cart_items'),
        ('web', '0035_alter_cartitems_belts_alter_cartitems_sunglasses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_belts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.belts')),
                ('to_sunglasses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sunglasses')),
                ('to_ties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ties')),
                ('to_wallets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.wallets')),
                ('to_watches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.watches')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
