# Generated by Django 4.1.3 on 2022-12-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_like_delete_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='to_belts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.belts'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_sunglasses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.sunglasses'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_ties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ties'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_wallets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.wallets'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_watches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.watches'),
        ),
    ]
