# Generated by Django 4.1.3 on 2022-12-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0034_remove_profile_cart_items'),
        ('web', '0037_alter_like_to_belts_alter_like_to_sunglasses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile'),
        ),
    ]
