# Generated by Django 4.1.3 on 2022-12-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_remove_like_to_watches_like_to_watches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='to_watches',
        ),
        migrations.AddField(
            model_name='like',
            name='to_watches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.watches'),
        ),
    ]
