# Generated by Django 4.1.3 on 2022-12-07 11:32

from django.db import migrations, models
import project_watches.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(upload_to='static/images/',),
        ),
    ]
