# Generated by Django 4.1.3 on 2022-12-07 12:40

from django.db import migrations, models
import project_watches.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_alter_belts_image_alter_sunglasses_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunglasses',
            name='model_year',
            field=models.PositiveIntegerField(validators=[project_watches.web.models.model_years_validator]),
        ),
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/',),
        ),
        migrations.AlterField(
            model_name='watches',
            name='year',
            field=models.PositiveIntegerField(validators=[project_watches.web.models.model_years_validator]),
        ),
    ]
