# Generated by Django 4.1.3 on 2022-12-07 14:32

from django.db import migrations, models
import project_watches.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_alter_sunglasses_model_year_alter_watches_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/',),
        ),
        migrations.AlterField(
            model_name='belts',
            name='price',
            field=models.PositiveIntegerField(validators=[project_watches.web.models.belt_price_validator]),
        ),
    ]
