# Generated by Django 4.1.3 on 2022-12-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_alter_belts_image_alter_belts_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
