# Generated by Django 4.1.3 on 2022-12-08 07:46

from django.db import migrations, models
import project_watches.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
