# Generated by Django 4.1.3 on 2022-12-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0040_alter_profile_image'),
        ('web', '0049_cart_ties_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ties',
            name='liked',
        ),
        migrations.AddField(
            model_name='watches',
            name='liked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile'),
        ),
    ]
