# Generated by Django 4.1.3 on 2022-12-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_remove_ties_liked_watches_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watches',
            name='liked',
        ),
    ]
