# Generated by Django 4.1.3 on 2022-12-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_alter_sunglasses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ties',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
