# Generated by Django 4.1.3 on 2022-12-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_alter_belts_image_alter_ties_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
