# Generated by Django 4.1.3 on 2022-12-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_alter_watches_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watches',
            options={'verbose_name': 'Watches'},
        ),
        migrations.AlterField(
            model_name='belts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='sunglasses',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='ties',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
