# Generated by Django 4.1.3 on 2022-12-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_alter_watches_options_alter_belts_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watches',
            options={'verbose_name_plural': 'Watches'},
        ),
    ]
