# Generated by Django 4.1.3 on 2022-12-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_alter_watches_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belts',
            options={'verbose_name_plural': 'Belts'},
        ),
        migrations.AlterModelOptions(
            name='sunglasses',
            options={'verbose_name_plural': 'Sunglasses'},
        ),
        migrations.AlterModelOptions(
            name='ties',
            options={'verbose_name_plural': 'Ties'},
        ),
        migrations.AlterModelOptions(
            name='wallets',
            options={'verbose_name_plural': 'Wallets'},
        ),
    ]
