# Generated by Django 4.1.3 on 2022-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_watches_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2022-12-18T00:00:00.000000'),
        ),
    ]
