# Generated by Django 4.1.3 on 2022-12-18 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_remove_watches_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
