# Generated by Django 4.1.3 on 2022-12-18 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_remove_watches_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 18, 7, 28, 59, 323657, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
