# Generated by Django 4.1.3 on 2022-12-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_watches_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watches',
            name='timestamp',
        ),
    ]
